---
title: "R Notebook"
output: html_notebook
editor_options:
  chunk_output_type: console
#editor_options: 
#  chunk_output_type: inline
---

```{r}
library("tidyverse")
library("caret")
```


```{r}
liver_raw <- read_tsv("../liver_design_to_ml.tsv")
panc_raw <- read_tsv("../pancreas_design_to_ml.tsv")
```



```{r}
panc_path <- lapply(panc_raw$pathology_categories, function(x) {
  unlist(str_split(x, ", ")) }) %>% unlist() %>% unique() %>% subset(!is.na(.))
panc_categories_wide <- sapply(panc_path, function(x) {
  grepl(x, panc_raw$pathology_categories)
  }) %>%
  as.data.frame() %>%
  rename_all(., function(x) paste(x, "pancreas", sep = "_"))

apply(panc_categories_wide, 2, table)

liver_path <- lapply(liver_raw$pathology_categories, function(x) {
  unlist(str_split(x, ", ")) }) %>% unlist() %>% unique() %>% subset(!is.na(.))
liver_categories_wide <- sapply(liver_path, function(x) {
  grepl(x, liver_raw$pathology_categories)
  }) %>%
  as.data.frame() %>%
  rename_all(., function(x) paste(x, "liver", sep = "_"))

apply(liver_categories_wide, 2, table)
```


```{r}
panc_dt <- panc_raw %>%
  select(-c("id", "subject_id", "is_validation_sample", "tissue_sample_id", "pathology_categories",
            "pathology_notes", "sampid", "smts", "smpthnts", "fat_percentage", "source",
            "tissue_highfat", "rows"))
#  bind_cols(panc_categories_wide[, c("saponification_pancreas",
#                                     "atrophy_pancreas",
#                                     "fibrosis_pancreas")])
```


```{r}
apply(liver_categories_wide, 2, table)
liver_dt <- liver_raw %>%
  select(-c("id", "subject_id", "is_validation_sample", "tissue_sample_id", "pathology_categories",
            "pathology_notes", "sampid", "smts", "smpthnts", "fat_percentage", "source",
            "tissue_highfat", "rows")) %>%
  bind_cols(liver_categories_wide[, c(#"necrosis_liver",
                                      "congestion_liver",
                                      "fibrosis_liver",
                                      #"inflammation_liver",
                                      "steatosis_liver")])
                                      #"cirrhosis_liver",
                                      #"hepatitis_liver")]) %>%
#  mutate(high_fat = Fat.Percentage_liver > median(Fat.Percentage_liver))
```


## ML Model
### Predict pancreas fat


```{r}
panc_x <- panc_dt %>% select(-over_fat_cutoff) %>% as.data.frame() %>%
  mutate_if(is.character, factor) %>%
  mutate_if(is.logical, factor)
panc_y_grp <- panc_dt %>% pull(over_fat_cutoff)

table(panc_y_grp)
```


```{r}
set.seed(2020)
trainIndex <- caret::createDataPartition(factor(panc_y_grp),
                                         p = .8, 
                                         list = FALSE, 
                                         times = 1)
```


#### Pancreat fat percentage as response

```{r}
# train_x <- dt_x[trainIndex[,1], ]
# train_y <- y_perc[trainIndex[,1]]
# 
# test_x <- dt_x[-trainIndex[,1], ]
# test_y <- y_perc[-trainIndex[,1]]
# 
# my_model <- train(train_x,
#                   train_y)
# 
# print(my_model)
# 
# test_pred <- predict(my_model, test_x)
# plot(test_y, test_pred, ylim=c(0,100), xlim = c(0,100))
# abline(0,1)
# 
# postResample(pred = test_pred, obs = test_y)
```


```{r}
iris2 <- iris %>%
  mutate(new_grp = rep(c("a", "b", "c", "d", "e"), 30)) %>%
  mutate_at("new_grp", factor) %>% 
  select(new_grp, everything())

set.seed(100)
mod <- train(iris2[, 1:5],
             iris2[,6])
                  #   method = "rf",  # Random forest
             #        trainControl = tr_ctrl)


```



### Pancreas fat group as response

```{r}
panc_train_x <- panc_x[trainIndex[,1], ]
panc_train_y <- factor(panc_y_grp[trainIndex[,1]])

panc_test_x <- panc_x[-trainIndex[,1], ]
panc_test_y <- factor(panc_y_grp[-trainIndex[,1]])

tr_ctrl <- trainControl(method="repeatedcv",
                        number = 10,
                        repeats = 3,
                        summaryFunction=twoClassSummary, 
                        classProbs=T,
                        savePredictions = TRUE)
set.seed(100)
panc_rf_crv <- train(panc_train_x,
                     panc_train_y,
                     method = "rf",  # Random forest
                     trainControl = tr_ctrl)

panc_rf_crv
plot(panc_rf_crv)
panc_test_pred <- predict(panc_rf_crv, panc_test_x, type = "prob")[,2]
panc_rf_roc <- pROC::roc(predictor = panc_test_pred,
          response = panc_test_y)

gbmImp <- varImp(panc_rf_crv, scale = FALSE)
gbmImp
plot(gbmImp, main = "Feature importance - random forest")
```



```{r}
set.seed(101)
panc_tb_crv <- train(panc_train_x,
                     panc_train_y,
                     method = "treebag",  # Bagged CART
                     trainControl = tr_ctrl)

panc_tb_crv
plot(panc_tb_crv)
panc_test_pred <- predict(panc_tb_crv, panc_test_x, type = "prob")[,2]
panc_tb_crv_roc <- pROC::roc(predictor = panc_test_pred,
          response = panc_test_y)

gbmImp <- varImp(panc_tb_crv, scale = FALSE)
gbmImp
```


```{r}
set.seed(102)
panc_bart_machine <- bartMachine(panc_train_x, panc_train_y)

panc_bart_machine

panc_test_pred <- predict(panc_bart_machine, panc_test_x, type = "prob")
panc_bart_roc <- pROC::roc(predictor = panc_test_pred,
          response = panc_test_y)

var_imp_bart <- investigate_var_importance(bart_machine, num_replicates_for_avg = 20)
```


```{r}
plot(panc_rf_roc, col = "green", main = "ROC curves: Panc fat pred by metadata and transcripts")
lines(panc_tb_crv_roc, col = "hotpink")
lines(panc_bart_roc, col = "orange")

legend("bottomright",
       legend = c(paste0("Random forest (AUC: ", round(panc_rf_roc$auc, 3), ")"),
                  paste0("Bagged CART (AUC: ", round(panc_tb_crv_roc$auc, 3), ")"),
                  paste0("BART (AUC: ", round(panc_bart_roc$auc, 3), ")")),
       col = c("green", "hotpink", "orange"),
       lty = 1, lwd = 1.4)
```



### Predict liver fat


```{r}
liver_x <- liver_dt %>% select(-over_fat_cutoff) %>% as.data.frame() %>%
  mutate_if(is.character, factor) %>%
  mutate_if(is.logical, factor)
#liver_y_perc <- liver_dt %>% pull(Fat.Percentage_liver)
liver_y_grp <- liver_dt %>% pull(over_fat_cutoff)

#summary(liver_y_perc)
table(liver_y_grp)
```


```{r}
set.seed(2020)
trainIndex <- caret::createDataPartition(factor(liver_y_grp),
                                         p = .8, 
                                         list = FALSE, 
                                         times = 1)
```


#### Liver fat percentage as response

```{r}
# train_x <- dt_x[trainIndex[,1], ]
# train_y <- y_perc[trainIndex[,1]]
# 
# test_x <- dt_x[-trainIndex[,1], ]
# test_y <- y_perc[-trainIndex[,1]]
# 
# my_model <- train(train_x,
#                   train_y)
# 
# print(my_model)
# 
# test_pred <- predict(my_model, test_x)
# plot(test_y, test_pred, ylim=c(0,100), xlim = c(0,100))
# abline(0,1)
# 
# postResample(pred = test_pred, obs = test_y)
```


### Liver fat group as response

```{r}
liver_train_x <- liver_x[trainIndex[,1], ]
liver_train_y <- factor(liver_y_grp[trainIndex[,1]])

liver_test_x <- liver_x[-trainIndex[,1], ]
liver_test_y <- factor(liver_y_grp[-trainIndex[,1]])

tr_ctrl <- trainControl(method="repeatedcv",
                        number = 10,
                        repeats = 3,
                        summaryFunction=twoClassSummary, 
                        classProbs=T,
                        savePredictions = TRUE)
set.seed(100)
liver_rf_crv <- train(liver_train_x,
                     liver_train_y,
                     method = "rf",  # Random forest
                     trainControl = tr_ctrl)

liver_rf_crv
plot(liver_rf_crv)
liver_test_pred <- predict(liver_rf_crv, liver_test_x, type = "prob")[,2]
liver_rf_roc <- pROC::roc(predictor = liver_test_pred,
          response = liver_test_y)

gbmImp <- varImp(liver_rf_crv, scale = FALSE)
tmp <- gbmImp[[1]]
tmp$name <- row.names(tmp)
tmp <- tmp[order(-tmp$Overall),]
tmp$name <- NULL
tmp <- tmp[1:20, ]

a <- tmp[1:20, ]

ggplot(a) +
  geom_point(aes(x = reorder(name, Overall), y = Overall), color = "blue") +
  geom_segment(aes(x = name, xend = name,
                   y = 0, yend = Overall)) +
  geom_point(aes(x = name, y = Overall), color = "blue") +
  coord_flip() +
  theme_classic() +
  xlab("features") + ylab("importance") +
  ggtitle("Feature importance top 20 - RF")

scatterplot(a$Overall, a$name)

gbmImp[[1]] <- tmp

plot(gbmImp, main = "Feature importance - random forest")
```



```{r}
set.seed(101)
liver_tb_crv <- train(liver_train_x,
                     liver_train_y,
                     method = "treebag",  # Bagged CART
                     trainControl = tr_ctrl)

liver_tb_crv
plot(liver_tb_crv)
liver_test_pred <- predict(liver_tb_crv, liver_test_x, type = "prob")[,2]
liver_tb_crv_roc <- pROC::roc(predictor = liver_test_pred,
          response = liver_test_y)

gbmImp <- varImp(liver_tb_crv, scale = FALSE)
gbmImp
```



```{r}
set.seed(102)
liver_bart_machine <- bartMachine(liver_train_x, liver_train_y)

liver_bart_machine

liver_test_pred <- predict(liver_bart_machine, liver_test_x, type = "prob")
liver_bart_roc <- pROC::roc(predictor = liver_test_pred,
          response = liver_test_y)

var_imp_bart <- investigate_var_importance(bart_machine, num_replicates_for_avg = 20)
```


```{r}
plot(liver_rf_roc, col = "green", main = "ROC curves: Liver fat pred by metadata and transcripts")
lines(liver_tb_crv_roc, col = "hotpink")
lines(liver_bart_roc, col = "orange")

legend("bottomright",
       legend = c(paste0("Random forest (AUC: ", round(liver_rf_roc$auc, 3), ")"),
                  paste0("Bagged CART (AUC: ", round(liver_tb_crv_roc$auc, 3), ")"),
                  paste0("BART (AUC: ", round(liver_bart_roc$auc, 3), ")")),
       col = c("green", "hotpink", "orange"),
       lty = 1, lwd = 1.4)
```




